# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: rocLin Group
email: maverick@roclineage.com
description: > # this means to ignore newlines until "baseurl:"
  CODE Centrally Organized Decentralized Entity brings business and programming together
  in the blockchain. Platform data solutions to build networks of trust for sustainable growth.
  Start up looking for new partners for change in business, nonprofit and personal data relationship management. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Include
include:
  - _pages

# Default YAML front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      title     : "rocLin group"
      header:
        hero_header : "roclin group"
        hero_text   : "all circles presuppose we'll end where we began, but only in our leaving can we come"
        hero_action : /

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# In _config.yml
