# ===============================
#   Jekyll Configuration File
# ===============================
# See: https://jekyllrb.com/docs/configuration/








# -------------------------------
#  Site settings
# -------------------------------

locale          : en-us
title           : rocLin Group
email           : maverick@roclineage.com
url             : https://roclin-grp.github.io

description: > # this means to ignore newlines until "baseurl:"
  CODE Centrally Organized Decentralized Entity brings business and programming together
  in the blockchain. Platform data solutions to build networks of trust for sustainable growth.
  Start up looking for new partners for change in business, nonprofit and personal data relationship management.

author:
  name          : Roclin Group
  email         : ""
  angellist     : ""
  facebook      : ""
  github        : ""
  google_plus   : ""
  twitter       : ""




# -------------------------------
#  Paths
# -------------------------------

source          : .
destination     : ./_site
collections_dir : .
plugins_dir     :  _plugins
layouts_dir     :  _layouts
data_dir        :  _data
includes_dir    :  _includes
collections:
  posts:
    output:   true




# -------------------------------
#  Handling Reading
# -------------------------------

safe                : false
encoding            : utf-8
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

include:
  - .htaccess
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

keep_files:
  - .git
  - .svn




# -------------------------------
#  Filtering Content
# -------------------------------

show_drafts     : null
limit_posts     : 0
future          : true
unpublished     : false




# -------------------------------
#  Plugins
# -------------------------------
# See: https://jekyllrb.com/docs/plugins/
# See: https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

whitelist: []
plugins_dir:
  - jekyll-feed
  - jekyll-paginate




# -------------------------------
#  Conversion
# -------------------------------

markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false




# -------------------------------
#  Serving
# -------------------------------

detach            : false
port              : 4000
host              : 127.0.0.1
baseurl           : "" #  does not include hostname
show_dir_listing  : false




# -------------------------------
#  Outputting
# -------------------------------

permalink         : date
paginate          : 10
paginate_path     : /page:num
timezone          : null

quiet             : false
verbose           : false

# See: https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      title: rocLin group
      layout: default
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  -
    scope:
      path: ""
      type: posts
    values:
      ref: post
      layout: post


liquid:
  error_mode: warn




# -------------------------------
#  Markdown Processors
# -------------------------------

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
